### ISSUE TITLE
(question) Must typecasting to Boolean return false? 

### ISSUE THREAD

**Issue by felipealbrecht** [slmgc/Nothing#1]
Hello, 
firstly, thank you for this nice library, I am looking forward to using it!

For me, the only thing that does not make sense is the typecasting to Boolean.
It is not orthogonal between these two equivalent call:

```js
Boolean(Nothing) // true
toBool(Nothing) // false
```

IMHO, I expect that a _Nothing_  must be false for itself.
For example, if I execute the following code, will the log be displayed in the console?

```js
function foo(a) {
 if (a) {
   console.log("I dont want it to be executed");
 }
}

foo(Nothing)
```

I took the assumption that it returns true from the documentation:
```
// Gotcha: typecasting of Nothing to a boolean returns true
Boolean(Nothing) // true
!!Nothing // true
```

**Comment by slmgc** [comment]
Hi, you are most welcome!

I believe `Nothing` should be consistent, that's right.`Number(Nothing)` returns `0`, `String(Nothing)` returns an empty string. And as both `""` and `0` are falsy values it would be logical and consistent to return `false` for boolean conversions. The issue is that there is no way to introduce a new falsy value besides existing ones: `false`, `null`, `undefined`, `0`, `NaN`, `''`, `document.all`.

To mitigate this `toBool` helper was introduced which basically calls `valueOf` to get `false`. Think of it as of `isNaN` helper function for `NaN` value, because `typeof NaN` returns `number` even though it's not and `typeof null` returns `object`.

Hope this answers your question about the reasoning.

**Comment by felipealbrecht** [comment]
Hello,  
thank you for the prompt answer.

I understand the reason and it looks like a limitation in the typescript/javascript than in your package.

What I (maybe you too) wish, is to have something similar to Python:
```python
 def __nonzero__(self):
   return False
```
but it seems such semantic it is not supported by typescript either javascript.
