### ISSUE TITLE
能不能给个中文版本的readme.md

### ISSUE THREAD

**Issue by xiaofan9** [slmgc/Nothing#4]
如题，讲道理，完全看英文完全搞不懂你这库能干啥。

**Comment by slmgc** [comment]
Do you have a suggestion how to make it better?

**Comment by xiaofan9** [comment]
不是，兄弟，我在尝试的理解你这库能做啥，有啥场景可以实现，但是我看了下你给的介绍和说明以及示例，没看懂能干啥，我甚至还翻了下源码，依旧没懂。

**Comment by xiaofan9** [comment]
我目前就发现，你这个库的nothing 加上任何值（数组，函数，对象等复杂数据结构除外）多是同样值返回

**Comment by slmgc** [comment]
I've just added a simple example to the readme, hope it helps!

**Comment by xiaofan9** [comment]
刚看了下，你示例的意思是 const a = Nothing 中的a 可以无限级联，而不报错？目前看来是只针对对象？
对了，能否给代码写上些注释？

**Comment by slmgc** [comment]
Yep, you are right, it won't throw an error if you try to access or call an undefined property or a method. It works with anything. I will add some comments to the source. Do you have any specific parts of the source code in mind which need an explanation?

**Comment by xiaofan9** [comment]
**有个问题，使用它的意义在哪里？**
     `const test = Nothing;
     a.v.c();`

    我没发现有什么使用意义。

我不需要特定的注释，我只是觉得一个库没有注释，是不合格的。

对了，我想成为这个库的贡献者，要怎么做呢？

**Comment by slmgc** [comment]
I believe it should be: `const test = Nothing; test.v.c();`, otherwise `a` is undefined.
You can use Nothing as a replacement for null/undefined values, that's the main purpose of it. It helps you by removing the null-checks and reducing the amount of the boilerplate code. Can be useful  as well as a mock object for writing tests.

I don't think there's much to contribute except for adding more use-cases to the examples and improving the docs.

**Comment by xiaofan9** [comment]
thinks
